# Generated by Django 5.1.1 on 2024-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dummy_field",
            field=models.CharField(blank=True, default="temp", max_length=10),
        ),
    ]
