# Generated by Django 5.1.1 on 2024-09-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_dummy_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dummy_field",
        ),
    ]
